my-shows:
  date-pattern: yyyy-MM-dd
  local-file-path: abc
server:
  port: 5000
  servlet:
    context-path: /myshows-service
spring:
  application:
    name: myshows-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create-drop